language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install .

# command to run tests
script:
  - parse_puppi examples/puppi_cmd/sessionA.cmd
  - parse_cimalog   -f examples/logs/p2780.cimalog_20200503 -v
  - parse_gbtlog  -f examples/logs/AGBT18B_226_150_log.txt -v
